/*
 * Copyright (c) 2026 Metra TikTok Patches
 * https://github.com/icysymmetra/tiktok-patches-for-morphe
 */
package app.morphe.extension.tiktok.settings;

import android.content.Context;
import android.content.res.Resources;

import app.morphe.extension.shared.Utils;

import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.zip.CRC32;

/**
 * Settings text in the phone's language.
 *
 * The English text stays in the code and doubles as the lookup key: its CRC32 names a
 * string resource that the Settings patch adds to TikTok for every bundled language
 * (extensions/tiktok/src/main/l10n, generated by scripts/gen-l10n.py). A language with no
 * entry, or a string nobody translated yet, falls back to the English text, so nothing
 * here can ever leave a label empty.
 */
public final class L10n {
    private static final String PREFIX = "mtp_";
    private static final Map<String, String> CACHE = new HashMap<>();
    private static String cachedLocale;

    private L10n() {
    }

    /** The resource name for {@code english}, the same one the generator writes. */
    public static String key(String english) {
        CRC32 crc = new CRC32();
        crc.update(english.getBytes(StandardCharsets.UTF_8));
        return PREFIX + String.format(Locale.ROOT, "%08x", crc.getValue());
    }

    public static String t(String english) {
        return t(Utils.getContext(), english);
    }

    /** Text that may be anything: only plain strings are looked up, styled text passes through. */
    public static CharSequence t(Context context, CharSequence text) {
        return text instanceof String ? t(context, (String) text) : text;
    }

    public static String t(Context context, String english) {
        if (english == null || english.isEmpty() || context == null) {
            return english;
        }
        Resources resources;
        try {
            resources = context.getResources();
        } catch (Throwable ignored) {
            return english;
        }
        if (resources == null) {
            return english;
        }
        String locale = String.valueOf(resources.getConfiguration().locale);
        synchronized (CACHE) {
            if (!locale.equals(cachedLocale)) {
                CACHE.clear();
                cachedLocale = locale;
            }
            String cached = CACHE.get(english);
            if (cached != null) {
                return cached;
            }
            String translated = english;
            try {
                int id = resources.getIdentifier(key(english), "string", context.getPackageName());
                if (id != 0) {
                    String value = resources.getString(id);
                    if (value != null && !value.isEmpty()) {
                        translated = value;
                    }
                }
            } catch (Throwable ignored) {
                // A resource the patch did not add, or a locale without it: the English stays.
            }
            CACHE.put(english, translated);
            return translated;
        }
    }

    /** {@link String#format} over the translated form of {@code english}. */
    public static String f(String english, Object... args) {
        return f(Utils.getContext(), english, args);
    }

    public static String f(Context context, String english, Object... args) {
        try {
            return String.format(Locale.getDefault(), t(context, english), args);
        } catch (Throwable ignored) {
            return String.format(Locale.ROOT, english, args);
        }
    }
}
