/*
 * Copyright 2026 Hushfeed contributors
 * https://github.com/SysAdminDoc/hushfeed
 *
 * Built on icysymmetra/tiktok-patches-for-morphe (GPL-3.0).
 */
package app.morphe.extension.tiktok.settings;

import java.util.HashMap;
import java.util.Map;

/**
 * The settings text in every language the bundle carries.
 *
 * Generated by scripts/gen-l10n.py from extensions/tiktok/src/main/l10n. Do not edit by
 * hand: edit the .tsv table and run the script.
 *
 * The translations live here rather than in TikTok's resources because merging them into
 * a resource table of 74,765 strings costs more patching memory than Morphe Manager gives
 * by default.
 */
public final class L10nTranslations {
    private L10nTranslations() {
    }

    /** The language tags with a table, lower case, in the order they are tried. */
    static final String[] LANGUAGES = {"de"};

    /** The table for one language tag, or null when nothing was translated into it. */
    static Map<String, String> of(String language) {
        switch (language) {
            case "de":
                return buildDe();
            default:
                return null;
        }
    }

    private static Map<String, String> buildDe() {
        Map<String, String> table = new HashMap<>(808);
        fillDe0(table);
        fillDe1(table);
        fillDe2(table);
        fillDe3(table);
        fillDe4(table);
        fillDe5(table);
        fillDe6(table);
        return table;
    }

    private static void fillDe0(Map<String, String> table) {
        table.put("%d languages excluded",
                "%d Sprachen ausgeschlossen");
        table.put("%s on",
                "%s aktiv");
        table.put("A hidden puzzle may be the cause.",
                "Ein ausgeblendetes Rätsel kann die Ursache sein.");
        table.put("A tap on a person in the Send to row only selects them. A second tap on the same person within four seconds sends the video.",
                "Ein Tippen auf eine Person in der Zeile „Senden an“ wählt sie nur aus. Ein zweites Tippen auf dieselbe Person innerhalb von vier Sekunden sendet das Video.");
        table.put("About Hushfeed",
                "Über Hushfeed");
        table.put("Add a block button to the video player that blocks the account that posted the current video in one tap. An undo action is shown after each block.",
                "Dem Videoplayer eine Schaltfläche hinzufügen, die das Konto hinter dem aktuellen Video mit einem Tippen blockiert. Nach jeder Blockierung wird eine Rückgängig-Aktion angezeigt.");
        table.put("Add a button beside the block control to send feedback about the current video.",
                "Neben der Blockieren-Schaltfläche eine Schaltfläche hinzufügen, um Feedback zum aktuellen Video zu senden.");
        table.put("Adds a custom option to TikTok's offline videos menu after restart.",
                "Fügt TikToks Menü für Offline-Videos nach einem Neustart eine eigene Option hinzu.");
        table.put("Ads, Shop, livestreams, and view limits.",
                "Werbung, Shop, Livestreams und Aufruflimits.");
        table.put("Advance when a video ends",
                "Weiterschalten, wenn ein Video endet");
        table.put("All available languages",
                "Alle verfügbaren Sprachen");
        table.put("All loaded tabs",
                "Alle geladenen Tabs");
        table.put("Allow screenshots and Circle to Search",
                "Screenshots und Circle to Search erlauben");
        table.put("Allowed bottom tabs",
                "Erlaubte untere Tabs");
        table.put("Allowed loaded tabs",
                "Erlaubte geladene Tabs");
        table.put("Also apply these filters to downloaded videos TikTok uses when the feed cannot load enough new items.",
                "Diese Filter auch auf heruntergeladene Videos anwenden, die TikTok nutzt, wenn der Feed nicht genug neue Beiträge laden kann.");
        table.put("Also override TikTok's region getters. Keeps your interface language. Requires Override SIM details and a restart; IP address and account rules still apply.",
                "Auch TikToks Regionsabfragen überschreiben. Deine Oberflächensprache bleibt erhalten. Erfordert „SIM-Angaben überschreiben“ und einen Neustart; IP-Adresse und Kontoregeln gelten weiterhin.");
        table.put("Always show publish date",
                "Veröffentlichungsdatum immer anzeigen");
        table.put("Always show the publish date in video author information. Requires restart.",
                "Das Veröffentlichungsdatum immer in den Angaben zum Video-Ersteller anzeigen. Erfordert einen Neustart.");
        table.put("App behavior",
                "App-Verhalten");
        table.put("Apply to video downloads and image downloads.",
                "Gilt für Video- und Bild-Downloads.");
        table.put("Arrange your feed and bottom tabs",
                "Ordne deine Feed-Tabs und unteren Tabs an");
        table.put("Auto translate comments",
                "Kommentare automatisch übersetzen");
        table.put("Auto translate, quick reactions, and copy options.",
                "Automatische Übersetzung, Schnellreaktionen und Kopieroptionen.");
        table.put("Automatic",
                "Automatisch");
        table.put("Automatic clear display",
                "Automatische freie Ansicht");
        table.put("Automatically translates loaded comment batches using TikTok's translation system.",
                "Übersetzt geladene Kommentare automatisch über TikToks Übersetzungssystem.");
        table.put("Back",
                "Zurück");
        table.put("Back up settings",
                "Einstellungen sichern");
        table.put("Backups and troubleshooting",
                "Sicherungen und Fehlerdiagnose");
        table.put("Black",
                "Schwarz");
        table.put("Block new TikTok tabs",
                "Neue TikTok-Tabs blockieren");
        table.put("Block new bottom tabs",
                "Neue untere Tabs blockieren");
        table.put("Blocked caption words",
                "Gesperrte Wörter in Beschreibungen");
        table.put("Blocked comment words",
                "Gesperrte Wörter in Kommentaren");
        table.put("Blocked creators",
                "Gesperrte Creator");
        table.put("Blocked sound ids",
                "Gesperrte Sound-IDs");
        table.put("Blocked sound names",
                "Gesperrte Sound-Namen");
        table.put("Browse",
                "Durchsuchen");
        table.put("Cancel",
                "Abbrechen");
        table.put("Caption background",
                "Untertitel-Hintergrund");
        table.put("Caption text size",
                "Textgröße der Untertitel");
        table.put("Captions, gestures and on-screen controls",
                "Untertitel, Gesten und Bildschirmelemente");
        table.put("Capture crash reports locally",
                "Absturzberichte lokal speichern");
        table.put("Choose 1-1000 videos. Values outside this range use the nearest valid limit. Restart TikTok after saving.",
                "Wähle 1 bis 1000 Videos. Werte außerhalb dieses Bereichs nutzen das nächstgelegene gültige Limit. Starte TikTok nach dem Speichern neu.");
        table.put("Choose a backup file. Your current settings are kept for Undo.",
                "Wähle eine Sicherungsdatei. Deine aktuellen Einstellungen bleiben zum Rückgängigmachen erhalten.");
        table.put("Choose what reaches your feed",
                "Wähle aus, was in deinem Feed erscheint");
        table.put("Choose which loaded TikTok bottom navigation tabs should stay visible.",
                "Wähle, welche geladenen Tabs der unteren TikTok-Navigation sichtbar bleiben.");
        table.put("Choose which loaded TikTok feed tabs should stay visible.",
                "Wähle, welche geladenen TikTok-Feed-Tabs sichtbar bleiben.");
        table.put("Choose which rows and controls appear",
                "Wähle sichtbare Zeilen und Bedienelemente");
        table.put("Clear",
                "Löschen");
        table.put("Clear buffered events and saved crash reports.",
                "Zwischengespeicherte Ereignisse und gespeicherte Absturzberichte löschen.");
        table.put("Clear diagnostic data",
                "Diagnosedaten löschen");
        table.put("Clear display delay",
                "Verzögerung der freien Ansicht");
        table.put("Clear the seen video history",
                "Verlauf gesehener Videos löschen");
        table.put("Clear the seen video history?",
                "Verlauf gesehener Videos löschen?");
        table.put("Cleared %1$s videos. Tap again to put them back.",
                "%1$s Videos gelöscht. Tippe erneut, um sie zurückzuholen.");
        table.put("Cleared. Tap again to put the record back.",
                "Gelöscht. Tippe erneut, um alles zurückzuholen.");
        table.put("Close",
                "Schließen");
        table.put("Comma separated account handles or user ids. These accounts are always skipped.",
                "Kontonamen oder Nutzer-IDs, durch Kommas getrennt. Diese Konten werden immer übersprungen.");
    }

    private static void fillDe1(Map<String, String> table) {
        table.put("Comma separated account handles or user ids. These accounts are always skipped. An entry between slashes, like /^news_/, is a pattern matched against the handle and the display name.",
                "Kommagetrennte Konto-Namen oder Nutzer-IDs. Diese Konten werden immer übersprungen. Ein Eintrag zwischen Schrägstrichen, etwa /^news_/, ist ein Muster für den @Namen und den Anzeigenamen.");
        table.put("Comma separated country codes, like GB, IE. Videos posted from anywhere else are hidden. Leave empty for all countries.",
                "Kommagetrennte Ländercodes, etwa GB, IE. Videos von überall sonst werden ausgeblendet. Leer lassen für alle Länder.");
        table.put("Comma separated country codes. Videos posted from these are hidden, whatever the list above says.",
                "Kommagetrennte Ländercodes. Videos von dort werden ausgeblendet, egal was die Liste darüber sagt.");
        table.put("Comma separated list of any other Inbox row titles to hide, matched exactly. Use this for anything not listed above.",
                "Liste weiterer Posteingangs-Zeilentitel, durch Kommas getrennt, die genau übereinstimmend ausgeblendet werden. Nutze das für alles, was oben nicht aufgeführt ist.");
        table.put("Comma separated names exactly as the share sheet shows them: friends in the Send to row, share targets such as Facebook, and actions such as Create group or Repost. Stable keys such as copy, save and dislike also work before the sheet opens.",
                "Namen, durch Kommas getrennt, genau so, wie das Teilen-Menü sie zeigt: Freunde in der Zeile „Senden an“, Ziele wie Facebook und Aktionen wie „Gruppe erstellen“ oder „Reposten“. Feste Schlüssel wie copy, save und dislike funktionieren auch, bevor das Menü sich öffnet.");
        table.put("Comma separated sound ids recorded by the player's sound button. Remove one to unblock it.",
                "Sound-IDs, durch Kommas getrennt, die über die Sound-Taste im Player erfasst wurden. Entferne eine, um sie freizugeben.");
        table.put("Comma separated usernames or display names whose comments are hidden.",
                "Nutzernamen oder Anzeigenamen, durch Kommas getrennt, deren Kommentare ausgeblendet werden.");
        table.put("Comma separated words or phrases. Matching captions are skipped. Case doesn't matter.",
                "Wörter oder Ausdrücke, durch Kommas getrennt. Passende Beschreibungen werden übersprungen. Groß- und Kleinschreibung spielt keine Rolle.");
        table.put("Comma separated words to match against a sound's name, like saxophone. Case does not matter.",
                "Wörter, durch Kommas getrennt, die mit dem Namen eines Sounds verglichen werden, zum Beispiel Saxophon. Groß- und Kleinschreibung spielt keine Rolle.");
        table.put("Comma separated. A comment is hidden if its text contains any of them. Case does not matter.",
                "Durch Kommas getrennt. Ein Kommentar wird ausgeblendet, wenn sein Text eines davon enthält. Groß- und Kleinschreibung spielt keine Rolle.");
        table.put("Comment media filename",
                "Dateiname für Kommentar-Medien");
        table.put("Comments and translation",
                "Kommentare und Übersetzung");
        table.put("Comments beside the video",
                "Kommentare neben dem Video");
        table.put("Compare gate reads with their previous values. Last recording: %d gates.",
                "Gate-Zugriffe mit ihren vorherigen Werten vergleichen. Letzte Aufzeichnung: %d Gates.");
        table.put("Confirm before following",
                "Vor dem Folgen bestätigen");
        table.put("Confirm before liking",
                "Vor dem Liken bestätigen");
        table.put("Confirm before sending to a friend",
                "Vor dem Senden an Freunde bestätigen");
        table.put("Confirm before sending, and hidden people and options.",
                "Bestätigung vor dem Senden sowie ausgeblendete Personen und Optionen.");
        table.put("Continue supported videos from where you stopped when you scroll back to them.",
                "Unterstützte Videos dort fortsetzen, wo du aufgehört hast, wenn du zu ihnen zurückscrollst.");
        table.put("Copy a quick report or save the full report as a file.",
                "Einen Kurzbericht kopieren oder den vollständigen Bericht als Datei speichern.");
        table.put("Copy comments without username",
                "Kommentare ohne Nutzernamen kopieren");
        table.put("Copy only the comment text when using TikTok's copy comment action.",
                "Beim Kopieren eines Kommentars über TikTok nur den Kommentartext übernehmen.");
        table.put("Copy report",
                "Bericht kopieren");
        table.put("Could not open settings section",
                "Einstellungsbereich konnte nicht geöffnet werden");
        table.put("Country ISO",
                "Länder-ISO");
        table.put("Country and network preferences",
                "Land und Netzwerkeinstellungen");
        table.put("Country, operator, locale and timezone.",
                "Land, Netzbetreiber, Sprache und Zeitzone.");
        table.put("Current: %1$s %2$s",
                "Aktuell: %1$s %2$s");
        table.put("Custom SIM details",
                "Eigene SIM-Angaben");
        table.put("Custom offline videos",
                "Eigene Offline-Videos");
        table.put("Dark",
                "Dunkel");
        table.put("Days to remember a video. Zero removes the age limit. History keeps at most 10,000 videos.",
                "Tage, die ein Video gemerkt wird. Null hebt die Altersgrenze auf. Der Verlauf behält höchstens 10.000 Videos.");
        table.put("Default playback speed",
                "Standard-Wiedergabegeschwindigkeit");
        table.put("Delete the local record of the videos you have watched.",
                "Die lokale Aufzeichnung der Videos löschen, die du gesehen hast.");
        table.put("Device language, then original",
                "Gerätesprache, dann Original");
        table.put("Diagnostics",
                "Diagnose");
        table.put("Disable analytics and tracking",
                "Analyse und Tracking abschalten");
        table.put("Disable long-press quick share",
                "Schnelles Teilen bei langem Drücken abschalten");
        table.put("Disable long-press repost",
                "Reposten bei langem Drücken abschalten");
        table.put("Do not translate languages",
                "Sprachen nicht übersetzen");
        table.put("Do nothing",
                "Nichts tun");
        table.put("Do you wish to proceed?",
                "Möchtest du fortfahren?");
        table.put("Double tap",
                "Doppeltippen");
        table.put("Download original photos",
                "Originalfotos herunterladen");
        table.put("Downloads",
                "Downloads");
        table.put("Enable diagnostic logging",
                "Diagnoseprotokoll einschalten");
        table.put("Enable hold-and-slide 2x lock",
                "2x-Sperre durch Halten und Wischen einschalten");
        table.put("Example: 310260",
                "Beispiel: 310260");
        table.put("Example: T-Mobile",
                "Beispiel: T-Mobile");
        table.put("Expand activity list",
                "Aktivitätsliste ausklappen");
        table.put("Export diagnostic report",
                "Diagnosebericht exportieren");
        table.put("Feature Gate Lab",
                "Feature Gate Lab");
        table.put("Feed filter",
                "Feed-Filter");
        table.put("Feed navigation",
                "Feed-Navigation");
        table.put("Feed tabs, bottom tabs, and Tako AI.",
                "Feed-Tabs, untere Tabs und Tako AI.");
        table.put("Filter bottom tabs",
                "Untere Tabs filtern");
        table.put("Filter comments by keyword",
                "Kommentare nach Stichwort filtern");
        table.put("Filter feed tabs",
                "Feed-Tabs filtern");
        table.put("Filter offline fallback videos",
                "Offline-Ersatzvideos filtern");
        table.put("Filters, translation and copy options",
                "Filter, Übersetzung und Kopieroptionen");
    }

    private static void fillDe2(Map<String, String> table) {
        table.put("Folder picker is not available",
                "Ordnerauswahl ist nicht verfügbar");
        table.put("Folder picker is not available on this device",
                "Ordnerauswahl ist auf diesem Gerät nicht verfügbar");
        table.put("For You",
                "Für dich");
        table.put("Forget seen videos after",
                "Gesehene Videos vergessen nach");
        table.put("Ghost mode",
                "Geistermodus");
        table.put("Hidden commenters",
                "Ausgeblendete Kommentierende");
        table.put("Hide AI generated videos",
                "KI-generierte Videos ausblenden");
        table.put("Hide CAPTCHA popups",
                "CAPTCHA-Popups ausblenden");
        table.put("Hide LIVE replays",
                "LIVE-Wiederholungen ausblenden");
        table.put("Hide Live entrance",
                "Live-Zugang ausblenden");
        table.put("Hide Series",
                "Serien ausblenden");
        table.put("Hide Tako AI",
                "Tako AI ausblenden");
        table.put("Hide TikTok Shop",
                "TikTok Shop ausblenden");
        table.put("Hide TikTok Shop updates and coupon messages.",
                "TikTok-Shop-Updates und Gutschein-Nachrichten ausblenden.");
        table.put("Hide TikTok Tako",
                "TikTok Tako ausblenden");
        table.put("Hide TikTok shop from feed.",
                "TikTok Shop aus dem Feed ausblenden.");
        table.put("Hide TikTok's exposed quick emoji row in supported comment inputs.",
                "TikToks Schnell-Emoji-Zeile in unterstützten Kommentarfeldern ausblenden.");
        table.put("Hide activity",
                "Aktivität ausblenden");
        table.put("Hide activity status",
                "Aktivitätsstatus ausblenden");
        table.put("Hide add people",
                "„Personen hinzufügen“ ausblenden");
        table.put("Hide archive",
                "Archiv ausblenden");
        table.put("Hide bottom tabs TikTok adds later unless you allow them.",
                "Untere Tabs ausblenden, die TikTok später hinzufügt, sofern du sie nicht erlaubst.");
        table.put("Hide browsing and LIVE puzzle dialogs. Login, account verification and any puzzle raised over a follow, like, comment or repost stay visible.",
                "Rätsel-Dialoge beim Stöbern und in LIVE ausblenden. Anmeldung, Kontobestätigung und jedes Rätsel, das bei Folgen, Liken, Kommentieren oder Reposten kommt, bleiben sichtbar.");
        table.put("Hide comment popup ads",
                "Werbe-Popups in Kommentaren ausblenden");
        table.put("Hide comments made of an image or a sticker instead of words.",
                "Kommentare ausblenden, die aus einem Bild oder Sticker statt aus Worten bestehen.");
        table.put("Hide comments that contain any of the words below, or that come from the accounts below.",
                "Kommentare ausblenden, die eines der Wörter unten enthalten oder von den Konten unten stammen.");
        table.put("Hide controls after each video starts. Tap to restore them.",
                "Bedienelemente nach dem Start jedes Videos ausblenden. Tippe, um sie wieder einzublenden.");
        table.put("Hide conversations",
                "Unterhaltungen ausblenden");
        table.put("Hide every direct message conversation. Leaves the Inbox empty apart from whatever else is still switched on.",
                "Jede Direktnachrichten-Unterhaltung ausblenden. Der Posteingang bleibt leer, abgesehen von allem, was sonst noch eingeschaltet ist.");
        table.put("Hide feed follow button",
                "Folgen-Schaltfläche im Feed ausblenden");
        table.put("Hide feed save button",
                "Speichern-Schaltfläche im Feed ausblenden");
        table.put("Hide feed search button",
                "Suchschaltfläche im Feed ausblenden");
        table.put("Hide floating promotion badges, coins, and timer banners on the homepage.",
                "Schwebende Werbe-Abzeichen, Münzen und Timer-Banner auf der Startseite ausblenden.");
        table.put("Hide floating promotions",
                "Schwebende Werbeaktionen ausblenden");
        table.put("Hide image video",
                "Bildbeiträge ausblenden");
        table.put("Hide image video from feed.",
                "Bildbeiträge aus dem Feed ausblenden.");
        table.put("Hide inserted cards",
                "Eingeschobene Karten ausblenden");
        table.put("Hide livestreams",
                "Livestreams ausblenden");
        table.put("Hide livestreams from feed.",
                "Livestreams aus dem Feed ausblenden.");
        table.put("Hide message requests",
                "Nachrichtenanfragen ausblenden");
        table.put("Hide new followers",
                "Neue Follower ausblenden");
        table.put("Hide paid partnerships",
                "Bezahlte Partnerschaften ausblenden");
        table.put("Hide people and options by name",
                "Personen und Optionen nach Name ausblenden");
        table.put("Hide picture comments",
                "Bild-Kommentare ausblenden");
        table.put("Hide playlist videos",
                "Playlist-Videos ausblenden");
        table.put("Hide promotional music",
                "Werbemusik ausblenden");
        table.put("Hide quick comment reactions",
                "Schnelle Kommentar-Reaktionen ausblenden");
        table.put("Hide rows by title",
                "Zeilen nach Titel ausblenden");
        table.put("Hide search",
                "Suche ausblenden");
        table.put("Hide sharing apps",
                "Apps zum Teilen ausblenden");
        table.put("Hide stories tray",
                "Story-Leiste ausblenden");
        table.put("Hide story",
                "Storys ausblenden");
        table.put("Hide story from feed.",
                "Storys aus dem Feed ausblenden.");
        table.put("Hide suggested account rows.",
                "Zeilen mit vorgeschlagenen Konten ausblenden.");
        table.put("Hide suggested accounts",
                "Vorgeschlagene Konten ausblenden");
        table.put("Hide surveys",
                "Umfragen ausblenden");
        table.put("Hide tabs TikTok adds later unless you allow them.",
                "Tabs ausblenden, die TikTok später hinzufügt, sofern du sie nicht erlaubst.");
        table.put("Hide the \"Search this image\" prompt TikTok shows over videos when it spots something to shop for.",
                "Den Hinweis „Dieses Bild suchen“ ausblenden, den TikTok über Videos zeigt, wenn es etwas zum Kaufen erkennt.");
        table.put("Hide the Activity row of likes and comments on your posts.",
                "Die Zeile „Aktivität“ mit Likes und Kommentaren zu deinen Beiträgen ausblenden.");
        table.put("Hide the Archive row.",
                "Die Zeile „Archiv“ ausblenden.");
    }

    private static void fillDe3(Map<String, String> table) {
        table.put("Hide the Live button in the top left corner of the feed.",
                "Die Live-Schaltfläche oben links im Feed ausblenden.");
        table.put("Hide the Message requests row.",
                "Die Zeile „Nachrichtenanfragen“ ausblenden.");
        table.put("Hide the New followers row.",
                "Die Zeile „Neue Follower“ ausblenden.");
        table.put("Hide the Send to row",
                "Zeile „Senden an“ ausblenden");
        table.put("Hide the Tako AI feed bubble above the profile button.",
                "Die Tako-AI-Blase im Feed über der Profil-Schaltfläche ausblenden.");
        table.put("Hide the TikTok Tako assistant conversation.",
                "Die Unterhaltung mit dem TikTok-Tako-Assistenten ausblenden.");
        table.put("Hide the action bar",
                "Aktionsleiste ausblenden");
        table.put("Hide the activity status control in the Inbox header.",
                "Das Element für den Aktivitätsstatus in der Kopfzeile des Posteingangs ausblenden.");
        table.put("Hide the add people icon in the Inbox header.",
                "Das Symbol zum Hinzufügen von Personen in der Kopfzeile des Posteingangs ausblenden.");
        table.put("Hide the arrow and its count in the right column.",
                "Pfeil und Zähler in der rechten Spalte ausblenden");
        table.put("Hide the avatar and follow button",
                "Bild und Folgen-Button ausblenden");
        table.put("Hide the bookmark and its count in the right column.",
                "Lesezeichen und Zähler in der rechten Spalte ausblenden");
        table.put("Hide the caption",
                "Beschreibung ausblenden");
        table.put("Hide the column on the right: avatar, like, comments, favourite, share and the music disc.",
                "Die Spalte rechts ausblenden: Avatar, Like, Kommentare, Favorit, Teilen und die Musikscheibe.");
        table.put("Hide the comments button",
                "Kommentar-Button ausblenden");
        table.put("Hide the counts on the right column",
                "Zahlen in der rechten Spalte ausblenden");
        table.put("Hide the creator's picture and the plus button at the top of the right column.",
                "Bild und Plus-Button oben in der rechten Spalte ausblenden");
        table.put("Hide the description under the creator's name on the feed.",
                "Die Beschreibung unter dem Namen des Creators im Feed ausblenden.");
        table.put("Hide the event badge",
                "Event-Abzeichen ausblenden");
        table.put("Hide the favourite button",
                "Favoriten-Button ausblenden");
        table.put("Hide the floating promotional badge over the feed.",
                "Das schwebende Werbe-Abzeichen über dem Feed ausblenden.");
        table.put("Hide the friend recommendation card and the other cards TikTok slots between videos.",
                "Die Freundesvorschlagskarte und die anderen Karten ausblenden, die TikTok zwischen Videos einschiebt.");
        table.put("Hide the heart and its count in the right column.",
                "Herz und Zähler in der rechten Spalte ausblenden");
        table.put("Hide the like button",
                "Like-Button ausblenden");
        table.put("Hide the music disc",
                "Musikplatte ausblenden");
        table.put("Hide the music line",
                "Musikzeile ausblenden");
        table.put("Hide the numbers under the like, comment, favourite and share buttons. The buttons stay.",
                "Blendet die Zahlen unter Like, Kommentar, Favorit und Teilen aus. Die Buttons bleiben.");
        table.put("Hide the playlist bar",
                "Playlist-Leiste ausblenden");
        table.put("Hide the playlist bar along the bottom of videos that belong to a series.",
                "Die Playlist-Leiste am unteren Rand von Videos ausblenden, die zu einer Serie gehören.");
        table.put("Hide the plus button under the creator's avatar on the action rail.",
                "Die Plus-Schaltfläche unter dem Avatar des Creators in der Aktionsleiste ausblenden.");
        table.put("Hide the question cards TikTok slides over a video near its end.",
                "Die Fragekarten ausblenden, die TikTok gegen Ende eines Videos einblendet.");
        table.put("Hide the row of story avatars across the top of the Inbox.",
                "Die Reihe der Story-Avatare oben im Posteingang ausblenden.");
        table.put("Hide the save button on the action rail.",
                "Die Speichern-Schaltfläche in der Aktionsleiste ausblenden.");
        table.put("Hide the search button in the top right corner of the feed.",
                "Die Suchschaltfläche oben rechts im Feed ausblenden.");
        table.put("Hide the search icon in the Inbox header.",
                "Das Suchsymbol in der Kopfzeile des Posteingangs ausblenden.");
        table.put("Hide the share button",
                "Teilen-Button ausblenden");
        table.put("Hide the speech bubble and its count in the right column.",
                "Sprechblase und Zähler in der rechten Spalte ausblenden");
        table.put("Hide the spinning music cover and the track name beside the caption.",
                "Das drehende Musik-Cover und den Titelnamen neben der Beschreibung ausblenden.");
        table.put("Hide the spinning record at the bottom of the right column.",
                "Drehende Platte unten in der rechten Spalte ausblenden");
        table.put("Hide the status bar",
                "Statusleiste ausblenden");
        table.put("Hide verified accounts",
                "Verifizierte Konten ausblenden");
        table.put("Hide video actions",
                "Videoaktionen ausblenden");
        table.put("Hide videos carrying TikTok's AI generated label.",
                "Videos mit TikToks Kennzeichnung für KI-generierte Inhalte ausblenden.");
        table.put("Hide videos marked as paid partnership or branded content.",
                "Videos ausblenden, die als bezahlte Partnerschaft oder Markeninhalt gekennzeichnet sind.");
        table.put("Hide videos posted as part of a playlist.",
                "Videos ausblenden, die als Teil einer Playlist veröffentlicht wurden.");
        table.put("Hide videos posted by verified accounts.",
                "Videos von verifizierten Konten ausblenden.");
        table.put("Hide videos that belong to a paid Series.",
                "Videos ausblenden, die zu einer bezahlten Serie gehören.");
        table.put("Hide videos you have already seen",
                "Bereits gesehene Videos ausblenden");
        table.put("Hide visual search prompt",
                "Bildersuche-Hinweis ausblenden");
        table.put("Highest",
                "Höchste");
        table.put("Home",
                "Startseite");
        table.put("Hushfeed cannot read the creator pattern %1$s",
                "Hushfeed kann das Creator-Muster %1$s nicht lesen");
        table.put("Hushfeed hid a TikTok puzzle. Turn off Hide CAPTCHA popups if something stops working.",
                "Hushfeed hat ein TikTok-Rätsel ausgeblendet. Schalte Rätsel-Dialoge ausblenden aus, wenn etwas nicht mehr funktioniert.");
        table.put("Inbox",
                "Posteingang");
        table.put("Included diagnostics",
                "Enthaltene Diagnosedaten");
        table.put("Includes all Morphe diagnostic events.",
                "Enthält alle Morphe-Diagnoseereignisse.");
        table.put("Interface",
                "Oberfläche");
        table.put("Keep a local record of what you have watched and drop those videos from later feed pages.",
                "Lokal festhalten, was du gesehen hast, und diese Videos aus späteren Feed-Seiten entfernen.");
        table.put("Keep automatic advance enabled. Pauses and open dialogs still stop scrolling. Restart after enabling it; use this switch to turn it off.",
                "Automatisches Weiterschalten eingeschaltet lassen. Pausen und offene Dialoge stoppen das Scrollen weiterhin. Nach dem Einschalten neu starten; zum Ausschalten diesen Schalter verwenden.");
        table.put("Keep captions in clear display",
                "Untertitel in der freien Ansicht behalten");
    }

    private static void fillDe4(Map<String, String> table) {
        table.put("Keep holding Like from opening TikTok's repost action.",
                "Verhindern, dass Halten von „Gefällt mir“ TikToks Repost-Aktion öffnet.");
        table.put("Keep long-pressing Share from opening TikTok's quick-share interaction.",
                "Verhindern, dass langes Drücken auf „Teilen“ TikToks schnelles Teilen öffnet.");
        table.put("Keep the clock and status icons off the screen while TikTok is open. Swipe down from the top to peek at them.",
                "Uhr und Statussymbole ausblenden, solange TikTok geöffnet ist. Wische von oben nach unten, um sie kurz zu sehen.");
        table.put("Leave maximum empty to keep it unlimited.",
                "Lass das Maximum leer, damit es unbegrenzt bleibt.");
        table.put("Links, privacy and player tools",
                "Links, Datenschutz und Wiedergabewerkzeuge");
        table.put("Long press",
                "Langes Drücken");
        table.put("Lower values require more likes per view. Zero disables this rule. One candidate may be kept to avoid an empty page.",
                "Niedrigere Werte verlangen mehr Likes pro Aufruf. Null schaltet diese Regel ab. Ein Kandidat kann bleiben, damit die Seite nicht leer ist.");
        table.put("Lowest",
                "Niedrigste");
        table.put("MENUS",
                "MENÜS");
        table.put("Make TikTok yours.",
                "Mach TikTok zu deinem TikTok.");
        table.put("Match locale and timezone to country",
                "Sprache und Zeitzone an das Land anpassen");
        table.put("Maximum",
                "Maximum");
        table.put("Maximum video length",
                "Maximale Videolänge");
        table.put("Maximum views per like",
                "Maximale Aufrufe pro Like");
        table.put("Min/Max comments",
                "Min/Max Kommentare");
        table.put("Min/Max favourites",
                "Min/Max Favoriten");
        table.put("Min/Max likes",
                "Min./Max. Likes");
        table.put("Min/Max shares",
                "Min/Max Teilen");
        table.put("Min/Max views",
                "Min./Max. Aufrufe");
        table.put("Minimum",
                "Minimum");
        table.put("Never from these countries",
                "Nie aus diesen Ländern");
        table.put("No additional languages excluded",
                "Keine weiteren Sprachen ausgeschlossen");
        table.put("No limit",
                "Keine Grenze");
        table.put("No preset selected",
                "Keine Vorgabe gewählt");
        table.put("Not interested button",
                "Schaltfläche „Kein Interesse“");
        table.put("Offline videos limit",
                "Limit für Offline-Videos");
        table.put("On mobile data",
                "Bei mobilen Daten");
        table.put("Only enable when recording logs to report an issue. Leaving it on for too long can make TikTok feel laggy and may lead to crashes.",
                "Nur einschalten, wenn du Protokolle für eine Fehlermeldung aufzeichnest. Bleibt es zu lange an, kann TikTok träge wirken und abstürzen.");
        table.put("Only from these countries",
                "Nur aus diesen Ländern");
        table.put("Only internal storage folders are supported",
                "Nur Ordner im internen Speicher werden unterstützt");
        table.put("Open TikTok home feed to detect loaded tabs.",
                "Öffne den TikTok-Startfeed, damit geladene Tabs erkannt werden.");
        table.put("Open TikTok home to detect loaded bottom tabs.",
                "Öffne die TikTok-Startseite, damit geladene untere Tabs erkannt werden.");
        table.put("Open comments",
                "Kommentare öffnen");
        table.put("Open external links directly",
                "Externe Links direkt öffnen");
        table.put("Open profile and story website links in your system browser instead of TikTok's in-app browser.",
                "Website-Links aus Profilen und Storys im Systembrowser öffnen statt in TikToks In-App-Browser.");
        table.put("Operator MCC/MNC",
                "Netzbetreiber MCC/MNC");
        table.put("Operator name",
                "Name des Netzbetreibers");
        table.put("Original language",
                "Originalsprache");
        table.put("Override SIM details",
                "SIM-Angaben überschreiben");
        table.put("Override store region (experimental)",
                "Store-Region überschreiben (experimentell)");
        table.put("Path, watermark, and offline videos.",
                "Pfad, Wasserzeichen und Offline-Videos.");
        table.put("People, shortcuts and sending controls",
                "Kontakte, Verknüpfungen und Versandoptionen");
        table.put("Photo destination",
                "Speicherort für Fotos");
        table.put("Photo filename",
                "Dateiname für Fotos");
        table.put("Play videos TikTok has classified without the overlay asking to be tapped through first.",
                "Von TikTok eingestufte Videos abspielen, ohne dass erst eine Warnung weggetippt werden muss.");
        table.put("Playback",
                "Wiedergabe");
        table.put("Promotions, popups, publish dates, and feed controls.",
                "Werbeaktionen, Popups, Veröffentlichungsdaten und Feed-Bedienelemente.");
        table.put("Put back %1$s videos",
                "%1$s Videos zurückgeholt");
        table.put("Quality, files and subtitles",
                "Qualität, Dateien und Untertitel");
        table.put("Quality, speed and automatic advance",
                "Qualität, Tempo und automatischer Wechsel");
        table.put("Recorded gate reads (%d)",
                "Aufgezeichnete Gate-Zugriffe (%d)");
        table.put("Recover the settings saved before the last restore or reset.",
                "Die vor der letzten Wiederherstellung oder Zurücksetzung gespeicherten Einstellungen zurückholen.");
        table.put("Region settings",
                "Regionseinstellungen");
        table.put("Remove ads from feed.",
                "Werbung aus dem Feed entfernen.");
        table.put("Remove feed ads",
                "Werbung im Feed entfernen");
        table.put("Remove secure window flags. Restart TikTok after changing.",
                "Sichere Fenster-Flags entfernen. Starte TikTok nach der Änderung neu.");
        table.put("Remove the Share via row.",
                "Die Zeile „Teilen über“ entfernen.");
        table.put("Remove the actions row from the share sheet.",
                "Die Aktionszeile aus dem Teilen-Menü entfernen.");
        table.put("Remove the row of friends from the top of the share sheet.",
                "Die Freundesreihe oben im Teilen-Menü entfernen.");
        table.put("Remove tracking parameters from shared links.",
                "Tracking-Parameter aus geteilten Links entfernen.");
    }

    private static void fillDe5(Map<String, String> table) {
        table.put("Remove watermark",
                "Wasserzeichen entfernen");
        table.put("Reset settings",
                "Einstellungen zurücksetzen");
        table.put("Restore defaults immediately. Your current settings are kept for Undo.",
                "Standardwerte sofort wiederherstellen. Deine aktuellen Einstellungen bleiben zum Rückgängigmachen erhalten.");
        table.put("Restore settings",
                "Einstellungen wiederherstellen");
        table.put("Resume videos after scrolling",
                "Videos nach dem Scrollen fortsetzen");
        table.put("Return after using a TikTok feature to see every gate read during the recording.",
                "Komm nach dem Verwenden einer TikTok-Funktion zurück, um jeden Gate-Zugriff während der Aufzeichnung zu sehen.");
        table.put("Rows, stories tray, and header controls.",
                "Zeilen, Story-Leiste und Kopfzeilen-Elemente.");
        table.put("SIM country preset",
                "SIM-Ländervorgabe");
        table.put("Sanitize sharing links",
                "Teilen-Links bereinigen");
        table.put("Save",
                "Speichern");
        table.put("Save JSON",
                "JSON speichern");
        table.put("Save SRT files with the video. Paired saves use Movies on Android 11+, Download on Android 10, and your video folder on older versions.",
                "SRT-Dateien zusammen mit dem Video speichern. Gemeinsame Speicherungen nutzen Movies ab Android 11, Download auf Android 10 und deinen Videoordner auf älteren Versionen.");
        table.put("Save every photo in the post directly from its source URL, without rendering it again.",
                "Jedes Foto des Beitrags direkt von seiner Quell-URL speichern, ohne es neu zu rendern.");
        table.put("Save patch settings and Feature Gate Lab rules to a JSON file.",
                "Patch-Einstellungen und Feature-Gate-Lab-Regeln in einer JSON-Datei speichern.");
        table.put("Save subtitles beside videos",
                "Untertitel neben Videos speichern");
        table.put("Save the latest available TikTok crash report for diagnostic export.",
                "Den neuesten verfügbaren TikTok-Absturzbericht für den Diagnose-Export speichern.");
        table.put("Search and override gate flags",
                "Gate-Flags suchen und überschreiben");
        table.put("Search local TikTok gate metadata and configure isolated typed overrides.",
                "Lokale TikTok-Gate-Metadaten durchsuchen und isolierte typisierte Überschreibungen einrichten.");
        table.put("Seconds. Zero keeps every length. If only quality rules reject a page, keep the nearest allowed candidate.",
                "Sekunden. Null lässt jede Länge zu. Lehnen nur Qualitätsregeln eine Seite ab, bleibt der nächstliegende erlaubte Kandidat erhalten.");
        table.put("Seen video history cleared",
                "Verlauf gesehener Videos gelöscht");
        table.put("Seen video history cleared. Tap again to put it back.",
                "Verlauf gesehener Videos gelöscht. Tippe erneut, um ihn zurückzuholen.");
        table.put("Seen video history put back",
                "Verlauf gesehener Videos zurückgeholt");
        table.put("Settings",
                "Einstellungen");
        table.put("Settings backup and diagnostic reports.",
                "Einstellungssicherung und Diagnoseberichte.");
        table.put("Settings saved. Restart TikTok to apply all changes.",
                "Einstellungen gespeichert. Starte TikTok neu, damit alle Änderungen wirken.");
        table.put("Share sheet",
                "Teilen-Menü");
        table.put("Sharing, playback, and gestures.",
                "Teilen, Wiedergabe und Gesten.");
        table.put("Show @username beside a video instead of the display name the creator chose.",
                "Zeigt @Benutzername neben einem Video statt des Anzeigenamens, den die Person gewählt hat.");
        table.put("Show Live search",
                "Live-Suche anzeigen");
        table.put("Show TikTok's search entry in the Live drawer where supported.",
                "TikToks Sucheingang im Live-Bereich anzeigen, wo das unterstützt wird.");
        table.put("Show a video preview thumbnail while dragging the seekbar.",
                "Beim Ziehen der Fortschrittsleiste ein Vorschaubild des Videos anzeigen.");
        table.put("Show block button on videos",
                "Blockieren-Schaltfläche auf Videos anzeigen");
        table.put("Show seekbar",
                "Fortschrittsleiste anzeigen");
        table.put("Show seekbar thumbnail",
                "Vorschaubild an der Fortschrittsleiste anzeigen");
        table.put("Show the country a video was posted from next to the creator's name.",
                "Das Land, aus dem ein Video veröffentlicht wurde, neben dem Namen des Creators anzeigen.");
        table.put("Show the current spoken caption while the other controls are hidden.",
                "Den aktuell gesprochenen Untertitel anzeigen, während die anderen Bedienelemente ausgeblendet sind.");
        table.put("Show the handle instead of the name",
                "@Namen statt Anzeigenamen zeigen");
        table.put("Show the native seekbar on videos where TikTok would normally hide it.",
                "Die native Fortschrittsleiste auch bei Videos anzeigen, bei denen TikTok sie sonst ausblendet.");
        table.put("Show the whole Activity and New followers lists instead of stopping at a View all button.",
                "Die vollständigen Listen „Aktivität“ und „Neue Follower“ anzeigen, statt bei einer Schaltfläche „Alle anzeigen“ zu enden.");
        table.put("Show where a video was posted",
                "Anzeigen, wo ein Video veröffentlicht wurde");
        table.put("Skip blocked sounds",
                "Gesperrte Sounds überspringen");
        table.put("Skip content warnings",
                "Inhaltswarnungen überspringen");
        table.put("Skip recorded LIVE broadcasts in the feed.",
                "Aufgezeichnete LIVE-Übertragungen im Feed überspringen.");
        table.put("Skip videos marked as using promotional music.",
                "Videos überspringen, die als Videos mit Werbemusik gekennzeichnet sind.");
        table.put("Skip videos that use a sound blocked with the player's sound button, or named below.",
                "Videos überspringen, deren Sound über die Sound-Taste im Player gesperrt wurde oder unten aufgeführt ist.");
        table.put("Source code and releases",
                "Quellcode und Versionen");
        table.put("Speed menu choices",
                "Auswahl im Geschwindigkeitsmenü");
        table.put("Split comment minimum width",
                "Mindestbreite für geteilte Kommentare");
        table.put("Start each new video at your default. A manual choice lasts until the video changes.",
                "Jedes neue Video mit deinem Standard starten. Eine manuelle Auswahl gilt, bis das Video wechselt.");
        table.put("Start feature gate recording",
                "Feature-Gate-Aufzeichnung starten");
        table.put("Sticker destination",
                "Speicherort für Sticker");
        table.put("Stop ByteDance AppLog events, AppsFlyer attribution, explicit Firebase screen reports and crash reporting from being sent. TikTok's own diagnostics go quiet with them.",
                "ByteDance-AppLog-Ereignisse, AppsFlyer-Attribution, explizite Firebase-Bildschirmberichte und Absturzmeldungen nicht mehr senden. TikToks eigene Diagnose verstummt damit ebenfalls.");
        table.put("Stop TikTok reporting that you viewed a story or a profile, that you are typing. Online status is unchanged. It cannot undo what the server has already recorded.",
                "TikTok nicht mehr melden lassen, dass du eine Story oder ein Profil angesehen hast oder gerade tippst. Der Online-Status bleibt unverändert. Was der Server bereits aufgezeichnet hat, lässt sich nicht rückgängig machen.");
        table.put("Stop feature gate recording",
                "Feature-Gate-Aufzeichnung beenden");
        table.put("Stop the brand animation that plays over the comments when what someone typed matches an advertiser's trigger.",
                "Stoppt die Markenanimation über den Kommentaren, wenn das Getippte zu einem Werbe-Auslöser passt.");
        table.put("Stop video looping",
                "Videoschleife beenden");
        table.put("Stop videos at the end instead of replaying them.",
                "Videos am Ende anhalten, statt sie zu wiederholen.");
        table.put("Subtitle language",
                "Untertitelsprache");
        table.put("Tap the feed Follow button twice within four seconds.",
                "Tippe die Folgen-Schaltfläche im Feed innerhalb von vier Sekunden zweimal an.");
        table.put("Tap the like heart twice within four seconds. Removing a like stays immediate.",
                "Tippe das Like-Herz innerhalb von vier Sekunden zweimal an. Das Entfernen eines Likes bleibt sofort.");
    }

    private static void fillDe6(Map<String, String> table) {
        table.put("The minimum or maximum comments on a video to show.",
                "Mindest- oder Höchstzahl an Kommentaren, damit ein Video gezeigt wird.");
        table.put("The minimum or maximum favourites of a video to show.",
                "Mindest- oder Höchstzahl an Favoriten, damit ein Video gezeigt wird.");
        table.put("The minimum or maximum likes of a video to show.",
                "Die Mindest- oder Höchstzahl an Likes, die ein Video zum Anzeigen haben darf.");
        table.put("The minimum or maximum shares of a video to show.",
                "Mindest- oder Höchstzahl an Teilungen, damit ein Video gezeigt wird.");
        table.put("The minimum or maximum views of a video to show.",
                "Die Mindest- oder Höchstzahl an Aufrufen, die ein Video zum Anzeigen haben darf.");
        table.put("The thumbs down on each comment blocks the account that posted it instead of disliking. The comment dims, an undo banner follows, and a second tap unblocks. Takes effect after a restart.",
                "Der Daumen runter an jedem Kommentar blockiert das Konto, das ihn geschrieben hat, statt ihn abzulehnen. Der Kommentar wird abgedunkelt, ein Rückgängig-Banner folgt, und ein zweites Tippen hebt die Blockierung auf. Wirkt nach einem Neustart.");
        table.put("There was nothing to clear",
                "Es gab nichts zu löschen");
        table.put("There was nothing to put back",
                "Es gab nichts zurückzuholen");
        table.put("This deletes the local record only. Your TikTok account history is not touched.",
                "Das löscht nur die lokale Aufzeichnung. Dein TikTok-Kontoverlauf bleibt unberührt.");
        table.put("Thumbs down blocks the commenter",
                "Daumen runter blockiert den Kommentierenden");
        table.put("TikTok default",
                "TikTok-Standard");
        table.put("TikTok default (2x hold, quick share)",
                "TikTok-Standard (2x halten, schnelles Teilen)");
        table.put("TikTok patches for Morphe, built on the Metra patches by icysymmetra and the community sets before them. Tap to open the project page.",
                "TikTok-Patches für Morphe, aufgebaut auf den Metra-Patches von icysymmetra und den Community-Sammlungen davor. Tippe, um die Projektseite zu öffnen.");
        table.put("TikTok refused the follow: %1$s",
                "TikTok hat das Folgen abgelehnt: %1$s");
        table.put("Tokens: {creator}, {date}, {video_id}, {index}. The file extension is kept automatically.",
                "Platzhalter: {creator}, {date}, {video_id}, {index}. Die Dateiendung bleibt automatisch erhalten.");
        table.put("Tokens: {creator}, {date}, {video_id}. The file extension is kept automatically.",
                "Platzhalter: {creator}, {date}, {video_id}. Die Dateiendung bleibt automatisch erhalten.");
        table.put("Tokens: {date}, {media_id}. Works for image and video stickers.",
                "Platzhalter: {date}, {media_id}. Gilt für Bild- und Video-Sticker.");
        table.put("Transparent",
                "Transparent");
        table.put("Undo last restore",
                "Letzte Wiederherstellung rückgängig machen");
        table.put("Unlimited",
                "Unbegrenzt");
        table.put("Up to 8 speeds from 0.5 to 3, separated by commas. Example: 0.5, 1, 1.5, 2, 2.5, 3. Leave empty for TikTok's list. Restart after changing this list.",
                "Bis zu 8 Geschwindigkeiten von 0,5 bis 3, durch Kommas getrennt. Beispiel: 0.5, 1, 1.5, 2, 2.5, 3. Leer lassen für TikToks Liste. Nach dem Ändern der Liste neu starten.");
        table.put("Use 0 for TikTok's size, or 12 to 48 sp. Applies to the next caption.",
                "0 für TikToks Größe oder 12 bis 48 sp. Gilt ab dem nächsten Untertitel.");
        table.put("Use TikTok's native hold, slide down, and release gesture to lock 2x speed.",
                "TikToks eigene Geste „Halten, nach unten wischen, loslassen“ verwenden, um die 2x-Geschwindigkeit zu fixieren.");
        table.put("Use TikTok's non-personalized search state instead of the saved account choice.",
                "TikToks nicht personalisierten Suchmodus statt der gespeicherten Kontoauswahl verwenden.");
        table.put("Use a default playback speed",
                "Standard-Wiedergabegeschwindigkeit verwenden");
        table.put("Use non-personalized search",
                "Nicht personalisierte Suche verwenden");
        table.put("Use the preset for TikTok's account and store region getters too. May affect search. Requires the locale option and a restart.",
                "Die Vorgabe auch für TikToks Konto- und Store-Regionsabfragen verwenden. Kann die Suche beeinflussen. Erfordert die Sprachoption und einen Neustart.");
        table.put("Use the selected country and operator values. Restart TikTok after changing region settings.",
                "Die gewählten Werte für Land und Netzbetreiber verwenden. Starte TikTok nach dem Ändern der Regionseinstellungen neu.");
        table.put("Use the split layout on wider screens. Restart TikTok after changing this option or unfolding if the old layout remains.",
                "Das geteilte Layout auf breiteren Bildschirmen verwenden. Starte TikTok nach dem Ändern dieser Option oder nach dem Aufklappen neu, falls das alte Layout bleibt.");
        table.put("Video destination",
                "Speicherort für Videos");
        table.put("Video download quality",
                "Qualität für Video-Downloads");
        table.put("Video filename",
                "Dateiname für Videos");
        table.put("Video playback quality",
                "Wiedergabequalität");
        table.put("Video quality, speed and automatic advance.",
                "Videoqualität, Geschwindigkeit und automatisches Weiterschalten.");
        table.put("Wait before hiding the controls.",
                "Wartezeit, bevor die Bedienelemente ausgeblendet werden.");
        table.put("Window width needed to enable the layout. Restart after changing.",
                "Fensterbreite, ab der das Layout aktiv wird. Nach dem Ändern neu starten.");
        table.put("YOUR EXPERIENCE",
                "DEIN TIKTOK");
        table.put("code %1$s",
                "Code %1$s");
        table.put("days",
                "Tage");
        table.put("dp",
                "dp");
        table.put("ms",
                "ms");
        table.put("sp",
                "sp");
        table.put("us, gb, jp, ...",
                "us, gb, jp, ...");
        table.put("videos",
                "Videos");
    }
}
